### ISSUE TITLE
EMA adds separate RG

### ISSUE THREAD

**Issue by pontushojer** [FrickTobias/BLR#203]
Currently the rule `tagbam` adds a RG tag using `samtools addreplacerg`. The mapper `ema` apparently also adds a RG which causes an error with `buildmolecules`.

Error in `buildmolecules`
```
Traceback (most recent call last):
  File "/home/phojer/miniconda3/envs/blr/bin/blr", line 11, in <module>
    load_entry_point('blr', 'console_scripts', 'blr')()
  File "/crex/proj/uppstore2018173/private/pontus/BLR-private/src/blr/__main__.py", line 45, in main
    module.main(args)
  File "/crex/proj/uppstore2018173/private/pontus/BLR-private/src/blr/cli/buildmolecules.py", line 27, in main
    library_type = infile.header.to_dict()["RG"][0]["LB"]
KeyError: 'LB'
```

Looking into the SAM header we see that there are two RG entries
```
(blr) [phojer@rackham3 test_ema]$ samtools view -H mapped.sorted.tag.bcmerge.mkdup.bam 
@HD	VN:1.6	SO:coordinate
@SQ	SN:chr22	LN:50818468
@RG	ID:rg1	SM:sample1
@RG	ID:1	SM:20	LB:blr	PU:unit1	PL:ILLUMINA
@PG	ID:ema	PN:ema	VN:0.6.2	CL:ema align -1 /dev/fd/63 -2 /dev/fd/62 -r ../../../chr22_testdata/chr22.fasta -t 4 -p 10x
@PG	ID:tagbam	PN:blr	CL:"/home/phojer/miniconda3/envs/blr/bin/blr tagbam mapped.sorted.bam -o -"
...
```

I have looked into the mappers and it seams all of them have options to add the RG tag directly in the mapping step. I will implement this and remove the `samtools addreplacerg`.

**Comment by pontushojer** [comment]
Fixed in commit `b76aa9cb5770b7bc6a6031314c578b8954618245`.
